[package]
name = "underdesk-music"
version = "0.1.0"
description = "A small independent desktop YouTube music playlist player."
authors = ["Underdesk Music"]
edition = "2021"

[lib]
name = "underdesk_music_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
